# Generated by Django 5.2.6 on 2025-09-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='monApp.produit')),
                ('rayons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(blank=True, through='monApp.Contenir', to='monApp.rayon'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='produits',
            field=models.ManyToManyField(blank=True, through='monApp.Contenir', to='monApp.produit'),
        ),
    ]
