# Generated by Django 5.2.6 on 2025-09-09 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.status'),
        ),
    ]
