# Generated by Django 5.2.6 on 2025-09-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFabricationProd',
            field=models.DateField(),
        ),
    ]
