# Generated by Django 5.2.6 on 2025-09-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_alter_produit_datefabricationprod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('produits', 'rayons')},
        ),
    ]
