# Generated by Django 5.2.6 on 2025-09-11 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0008_alter_contenir_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFabricationProd',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
