# Generated by Django 5.2.6 on 2025-09-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0009_alter_produit_datefabricationprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon'),
        ),
    ]
