# Generated by Django 5.2.6 on 2025-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0010_alter_contenir_produits_alter_contenir_rayons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
