# Generated by Django 5.2.6 on 2025-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0011_alter_contenir_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
