# Generated by Django 5.2.6 on 2025-09-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0012_alter_contenir_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit'),
        ),
    ]
