# Generated by Django 5.2.6 on 2025-10-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0013_alter_contenir_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenir',
            name='produits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon'),
        ),
    ]
